module.exports = {
    CONNECTION_STRING: process.env.CONNECTION_STRING,
    ACCESS_SECRET_TOKEN: process.env.ACCESS_SECRET_TOKEN,
    REFRESH_SECRET_TOKEN: process.env.REFRESH_SECRET_TOKEN,
    R2_BUCKET_NAME: process.env.R2_BUCKET_NAME,
    R2_ACCOUNT_ID: process.env.R2_ACCOUNT_ID,
    R2_WRITE_ACCESS_KEY_ID: process.env.R2_WRITE_ACCESS_KEY_ID,
    R2_WRITE_SECRET_ACCESS_KEY: process.env.R2_WRITE_SECRET_ACCESS_KEY,
    PUBLIC_URL_BASE: process.env.PUBLIC_URL_BASE,
}